-- This file is automatically loaded by plugins.config

vim.opt.autoindent = true
vim.opt.autowrite = true -- Enable auto write
vim.opt.backspace = "indent,eol,start"
vim.opt.backup = false
vim.opt.breakindent = true
vim.opt.clipboard = "unnamedplus" -- Sync with system clipboard
vim.opt.completeopt = "menu,menuone,noselect"
vim.opt.cursorline = true -- Enable highlighting of the current line
vim.opt.encoding = "utf-8"
vim.opt.eol = false -- show if there's no eol char
vim.opt.expandtab = true -- expand tab to spaces
vim.opt.fileencoding = "utf-8"
vim.opt.foldcolumn = "1"
vim.opt.foldenable = true
vim.opt.foldlevel = 99 -- limit folding to 4 levels
vim.opt.foldlevelstart = 99 -- limit folding to 4 levels
vim.opt.foldmethod = 'syntax' -- use language syntax to generate folds
vim.opt.formatoptions = 'jcroqlnt' -- q  - comment formatting; n - numbered lists; j - remove comment when joining lines; 1 - don't break after one-letter word
vim.opt.grepformat = "%f:%l:%c:%m"
vim.opt.grepprg = "rg --vimgrep"
vim.opt.history = 100
vim.opt.ignorecase = true -- ignore letter case when searching
vim.opt.incsearch = true -- starts searching as soon as typing, without enter needed
vim.opt.infercase = true
vim.opt.laststatus = 2
vim.opt.list = false -- do not display white characters
vim.opt.matchtime = 2 -- delay before showing matching paren
vim.opt.modelines = 0
vim.opt.mouse = "a" -- Enable mouse mode
vim.opt.mps = vim.o.mps .. ",<:>"
vim.opt.number = true -- line number on the left
vim.opt.numberwidth = 3 -- always reserve 3 spaces for line number
vim.opt.preserveindent = true
vim.opt.pumheight = 10
vim.opt.relativenumber = true -- Relative line numbers
vim.opt.scrolloff = 4 -- Lines of context
vim.opt.shiftround = true -- Round indent
vim.opt.shiftwidth = 2 -- indentation rule
vim.opt.shortmess:append { C = true }
vim.opt.shortmess:append { W = true, I = true, c = true }
vim.opt.showbreak= '↪' -- character to show when line is broken
vim.opt.showcmd = true -- display command in bottom bar
vim.opt.showmatch = true
vim.opt.showmode = false -- Dont show mode since we have a statusline
vim.opt.sidescrolloff = 8 -- Columns of context
vim.opt.signcolumn = 'yes' -- Always show the signcolumn, otherwise it would shift the text each time
vim.opt.smartcase = true -- case insentive unless capitals used in search
vim.opt.smartindent = true
vim.opt.smoothscroll = true
vim.opt.softtabstop = 2
vim.opt.spelllang = { "en" }
vim.opt.splitkeep = "screen"
vim.opt.startofline = true
vim.opt.swapfile = false -- do not use swap file
vim.opt.synmaxcol = 300
vim.opt.tabstop = 2
vim.opt.termguicolors = true -- True color support
vim.opt.timeout = false
vim.opt.ttimeout = true
vim.opt.ttimeoutlen = 100
vim.opt.undodir = os.getenv("HOME") .. "/.local/state/nvim/undo"
vim.opt.undofile = true
vim.opt.undofile = true
vim.opt.undolevels = 10000
vim.opt.updatetime = 200 -- Save swap file and trigger CursorHold
vim.opt.wildignore = 'deps,.svn,CVS,.git,.hg,*.o,*.a,*.class,*.mo,*.la,*.so,*.obj,*.swp,*.jpg,*.png,*.xpm,*.gif,.DS_Store,*.aux,*.out,*.toc'
vim.opt.wildmenu = true -- on TAB, complete options for system command
vim.opt.wildmode = "longest:full,full" -- Command-line completion mode
vim.opt.winminwidth = 5 -- Minimum window width
vim.opt.wrap = false --do not wrap lines even if very long
vim.opt.writebackup = false
