vim.opt.autowrite = true -- Enable auto write
vim.opt.backspace = "indent,eol,start"
vim.opt.clipboard = "unnamedplus" -- Sync with system clipboard
vim.opt.completeopt = "menu,menuone,noselect"
vim.opt.conceallevel = 2 -- Hide * markup for bold and italic, but not markers with substitutions
vim.opt.cursorline = true -- Enable highlighting of the current line
vim.opt.expandtab = true -- Use spaces instead of tabs
vim.opt.fillchars = { foldopen = "", foldclose = "", eob = " " }
vim.opt.foldcolumn = "auto"
vim.opt.foldenable = true -- enable fold for nvim-ufo
vim.opt.foldlevel = 99 -- limit folding to 4 levels
vim.opt.foldlevelstart = 99 -- start with all code unfolded
vim.opt.foldmethod = "syntax" -- use language syntax to generate folds
vim.opt.formatoptions = "jcroqlnt" -- tcqj
vim.opt.grepprg = "rg --vimgrep"
vim.opt.laststatus = 3 -- global statusline
vim.opt.list = true
vim.opt.mouse = "a" -- Enable mouse mode
vim.opt.mps:append("<:>")
vim.opt.number = true -- line number on the left
vim.opt.preserveindent = true
vim.opt.pumblend = 10 -- Popup blend
vim.opt.pumheight = 10 -- Maximum number of entries in a popup
vim.opt.relativenumber = true -- Relative line numbers
vim.opt.shiftround = true -- Round indent
vim.opt.shiftwidth = 2 -- Size of an indent
vim.opt.showbreak= '↪' -- character to show when line is broken
vim.opt.showmode = false -- Dont show mode since we have a statusline
vim.opt.sidescrolloff = 8 -- Columns of context
vim.opt.signcolumn = 'yes' -- Always show the signcolumn, otherwise it would shift the text each time
vim.opt.smartcase = true -- case insentive unless capitals used in search
vim.opt.smartindent = true -- Insert indents automatically
vim.opt.smoothscroll = true
vim.opt.softtabstop = 2
vim.opt.spelllang = { "en", "cjk" }
vim.opt.tabstop = 2 -- Number of spaces tabs count for
vim.opt.termguicolors = true -- True color support
vim.opt.timeoutlen = 300
vim.opt.undodir = os.getenv("HOME") .. "/.local/state/nvim/undo"
vim.opt.undofile = true
vim.opt.updatetime = 200 -- Save swap file and trigger CursorHold
vim.opt.virtualedit = "block" -- Allow cursor to move where there is no text in visual block mode
vim.opt.wildmenu = true -- on TAB, complete options for system command
vim.opt.wrap = false -- Disable line wrap
